apiVersion: apps/v1
kind: Deployment 
metadata:
  name: iutcloud2
  labels:
    app: qtt-cloud
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qtt-cloud
  template:
    metadata:
      labels:
        app: qtt-cloud
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 8080
